/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_CPrint */

#ifndef _Included_utils_CPrint
#define _Included_utils_CPrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_CPrint
 * Method:    cprint
 * Signature: (Ljava/lang/String;Ljava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_utils_CPrint_cprint
  (JNIEnv *, jobject, jstring, jstring, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
